### ISSUE TITLE
Bump `0.0.0` to `1.0.0` - it's stable

### ISSUE THREAD

**Issue by itay-grudev** [will-wow/webpacker-svelte#4]
Dear Will,

I've been running `0.0.0` on production with lots of users. I haven't seen any problems so far an I believe it's time to give your gem the honour of calling it stable. I think you should call it `1.0.0`.

**Comment by will-wow** [comment]
@itay-grudev wow, apparently it's so stable I missed the notification about this! I'm so glad to hear this is working well for you, and you're right that it seems like it's time to bump the version to 1.0.0! 

It's been a while since I published a gem, but the version bump to 1.0.0 seems to be working on my test repo. Please let me know if you run into any problems!
